name: survey_js_core
description: Flutter package for parsing survey json.
version: 0.0.2+1
author: Deep Naik <deep.n@solutelabs.com>
homepage: https://github.com/solutelabs/survey_js_core

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


